In [2]:
import pandas as pd

# CSV File can be downloaded using the below link:
# SG - https://smu-my.sharepoint.com/:x:/g/personal/dvhanley_2019_scis_smu_edu_sg/EYUmv94oJD5IkPhkWPU5EKgBpjCUs5DeDCRGqntYUgE6kQ?e=NTWo5a

tweets_df = pd.read_csv("../singapore_tweets.csv")
tweets_df.head()

,url,date,rawContent,renderedContent,id,user,replyCount,retweetCount,likeCount,quoteCount,...,inReplyToTweetId,inReplyToUser,mentionedUsers,coordinates,place,hashtags,cashtags,card,viewCount,vibe
0,https://twitter.com/khainad/status/16307166453...,2023-02-28 23:48:40+00:00,Both my girls contracted covid and they’re jus...,Both my girls contracted covid and they’re jus...,1630716645357522944,https://twitter.com/khainad,1,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,52.0,NaN
1,https://twitter.com/MattHarrisEdD/status/16306...,2023-02-28 22:30:03+00:00,5 Tips for CyberSafety for Families During COV...,5 Tips for CyberSafety for Families During COV...,1630696860598915075,https://twitter.com/MattHarrisEdD,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,"['Edtech', 'GlobalEd', 'elearning', 'edutech']",NaN,SummaryCard(title='5 Tips for CyberSafety for ...,72.0,NaN
2,https://twitter.com/Chindyagung1/status/163066...,2023-02-28 20:33:20+00:00,@AlgodTrading Imagine if you take vaccinate an...,@AlgodTrading Imagine if you take vaccinate an...,1630667487745576960,https://twitter.com/Chindyagung1,0,0,0,0,...,1.630642e+18,https://twitter.com/AlgodTrading,"[User(username='AlgodTrading', id=117864028365...",NaN,NaN,NaN,NaN,NaN,20.0,NaN
3,https://twitter.com/mfame_guru/status/16306590...,2023-02-28 19:59:48+00:00,Hong Kong is scrapping its COVID-19 mask manda...,Hong Kong is scrapping its COVID-19 mask manda...,1630659051599065088,https://twitter.com/mfame_guru,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SummaryCard(title='Hong Kong Ends One of World...,16.0,NaN
4,https://twitter.com/mfame_guru/status/16306565...,2023-02-28 19:50:00+00:00,The geopolitical uncertainty brought by the Uk...,The geopolitical uncertainty brought by the Uk...,1630656583733596160,https://twitter.com/mfame_guru,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SummaryCard(title='What are Business Leaders D...,7.0,NaN

In [3]:
df_new = tweets_df[['date', 'renderedContent', 'user']]
df_new.head()

,date,renderedContent,user
0,2023-02-28 23:48:40+00:00,Both my girls contracted covid and they’re jus...,https://twitter.com/khainad
1,2023-02-28 22:30:03+00:00,5 Tips for CyberSafety for Families During COV...,https://twitter.com/MattHarrisEdD
2,2023-02-28 20:33:20+00:00,@AlgodTrading Imagine if you take vaccinate an...,https://twitter.com/Chindyagung1
3,2023-02-28 19:59:48+00:00,Hong Kong is scrapping its COVID-19 mask manda...,https://twitter.com/mfame_guru
4,2023-02-28 19:50:00+00:00,The geopolitical uncertainty brought by the Uk...,https://twitter.com/mfame_guru

In [4]:
# for Quote Network

userlist = ['https://twitter.com/ChannelNewsAsia', 'https://twitter.com/MothershipSG', 'https://twitter.com/DannyQuah', 'https://twitter.com/BogdziewiczM', 'https://twitter.com/DTrain', 'https://twitter.com/leejanhau', 'https://twitter.com/dwallbank', 'https://twitter.com/temptempholder', 'https://twitter.com/theforceawaken']
for user in userlist:
    username = user.split('/')[-1]
    user_tweets = df_new[tweets_df['user'] == user]
    
    user_tweets.to_csv(f'{username}_tweets.csv', index=False)
    user_tweets.to_csv(f'{username}_tweets.txt', index=False, sep='\t')

In [5]:
# for Reply Network

userlist = ['https://twitter.com/traintheteacher', 'https://twitter.com/daphnemaia', 'https://twitter.com/realDonaldTrump', 'https://twitter.com/mrbrown', 'https://twitter.com/_rodahidup', 'https://twitter.com/bobby_the_great']
for user in userlist:
    username = user.split('/')[-1]
    user_tweets = df_new[df_new['user'] == user]
    
    user_tweets.to_csv(f'{username}_tweets.csv', index=False)
    user_tweets.to_csv(f'{username}_tweets.txt', index=False, sep='\t')